// SPDX-License-Identifier: GPL-2.0-or-later
// Every command registered in the Tauri invoke handler must be allowed by the main
// capability and carry its autogenerated permission file. Tauri 2 rejects an invoke
// of an unlisted app command at the IPC boundary, which the client only sees as a
// generic failure: the phone's QR scanner button did exactly that (run 34620877616).
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function registeredCommands() {
  const source = readFileSync(join(root, 'src-tauri/src/lib.rs'), 'utf8');
  const block = /tauri::generate_handler!\[([\s\S]*?)\]/u.exec(source);
  assert.ok(block, 'invoke handler block missing');
  const commands = [...block[1].matchAll(/(?:commands|taskbar|language)::([a-z_]+)/gu)].map((match) => match[1]);
  assert.ok(commands.length >= 5, 'unexpectedly few registered commands');
  return commands;
}

test('every registered command is allowed by the main capability', () => {
  const capability = JSON.parse(readFileSync(join(root, 'src-tauri/capabilities/main.json'), 'utf8'));
  assert.equal(capability.identifier, 'main');
  const permissions = new Set(capability.permissions);
  for (const command of registeredCommands()) {
    const permission = `allow-${command.replaceAll('_', '-')}`;
    assert.ok(permissions.has(permission), `${command} is registered but ${permission} is not in capabilities/main.json`);
  }
});

test('every registered command has its autogenerated permission file', () => {
  for (const command of registeredCommands()) {
    const path = join(root, 'src-tauri/permissions/autogenerated', `${command}.toml`);
    assert.ok(existsSync(path), `${path} is missing`);
    const text = readFileSync(path, 'utf8');
    assert.match(text, new RegExp(`identifier = "allow-${command.replaceAll('_', '-')}"`, 'u'));
    assert.match(text, new RegExp(`commands\\.allow = \\["${command}"\\]`, 'u'));
  }
});

test('the capability does not allow a command that is not registered', () => {
  const capability = JSON.parse(readFileSync(join(root, 'src-tauri/capabilities/main.json'), 'utf8'));
  const registered = new Set(registeredCommands().map((command) => `allow-${command.replaceAll('_', '-')}`));
  for (const permission of capability.permissions) {
    assert.ok(registered.has(permission), `${permission} allows a command that the handler does not register`);
  }
});
