// SPDX-License-Identifier: GPL-2.0-or-later
// Every command registered in the Tauri invoke handler must be allowed by the main
// capability and carry its autogenerated permission file. Tauri 2 rejects an invoke
// of an unlisted app command at the IPC boundary, which the client only sees as a
// generic failure: the phone's QR scanner button did exactly that (run 34620877616).
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function registeredCommands() {
  const source = readFileSync(join(root, 'src-tauri/src/lib.rs'), 'utf8');
  const block = /tauri::generate_handler!\[([\s\S]*?)\]/u.exec(source);
  assert.ok(block, 'invoke handler block missing');
  const commands = [...block[1].matchAll(/(?:commands|taskbar|language)::([a-z_]+)/gu)].map((match) => match[1]);
  assert.ok(commands.length >= 5, 'unexpectedly few registered commands');
  return commands;
}

test('every registered command is allowed by the main capability', () => {
  const capability = JSON.parse(readFileSync(join(root, 'src-tauri/capabilities/main.json'), 'utf8'));
  assert.equal(capability.identifier, 'main');
  const permissions = new Set(capability.permissions);
  for (const command of registeredCommands()) {
    const permission = `allow-${command.replaceAll('_', '-')}`;
    assert.ok(permissions.has(permission), `${command} is registered but ${permission} is not in capabilities/main.json`);
  }
});

test('every registered command has its autogenerated permission file', () => {
  for (const command of registeredCommands()) {
    const path = join(root, 'src-tauri/permissions/autogenerated', `${command}.toml`);
    assert.ok(existsSync(path), `${path} is missing`);
    const text = readFileSync(path, 'utf8');
    assert.match(text, new RegExp(`identifier = "allow-${command.replaceAll('_', '-')}"`, 'u'));
    assert.match(text, new RegExp(`commands\\.allow = \\["${command}"\\]`, 'u'));
  }
});

test('permission files retain the exact generator boilerplate before native build provenance is captured', () => {
  for (const command of registeredCommands()) {
    const name = command.replaceAll('_', '-');
    const expected = `# Automatically generated - DO NOT EDIT!\n\n[[permission]]\nidentifier = "allow-${name}"\ndescription = "Enables the ${command} command without any pre-configured scope."\ncommands.allow = ["${command}"]\n\n[[permission]]\nidentifier = "deny-${name}"\ndescription = "Denies the ${command} command without any pre-configured scope."\ncommands.deny = ["${command}"]`;
    const actual = readFileSync(join(root, 'src-tauri/permissions/autogenerated', `${command}.toml`), 'utf8').replace(/\r\n/gu, '\n').trimEnd();
    assert.equal(actual, expected, `${command}: custom generated text would make native build source drift`);
  }
});

test('the capability does not allow a command that is not registered', () => {
  const capability = JSON.parse(readFileSync(join(root, 'src-tauri/capabilities/main.json'), 'utf8'));
  const registered = new Set(registeredCommands().map((command) => `allow-${command.replaceAll('_', '-')}`));
  for (const permission of capability.permissions) {
    assert.ok(registered.has(permission), `${permission} allows a command that the handler does not register`);
  }
});

// The phone page subscribes to the device-state plugin's empty request-change
// event. Tauri 2 checks plugin commands against the ACL too, and this one was
// never granted, so the subscription failed silently and the request screen
// only caught up on its five-second poll (1.5.0 on a real phone: notification
// at 09:57:14.8, card at the next poll, 09:57:18.0). The grant is the listener
// pair and nothing else: the plugin's native commands must stay reachable only
// through the app's own typed commands.
const wakeCapability = 'src-tauri/capabilities/android-request-wake.json';
const wakePermissions = ['device-state:allow-register-listener', 'device-state:allow-remove-listener'];

test('the phone page may subscribe to the native request wake and to nothing else of device-state', () => {
  const capability = JSON.parse(readFileSync(join(root, wakeCapability), 'utf8'));
  assert.equal(capability.identifier, 'android-request-wake');
  assert.deepEqual(capability.platforms, ['android']);
  assert.deepEqual(capability.windows, ['main']);
  assert.equal(capability.remote, undefined, 'remote content must never reach the plugin');
  assert.deepEqual([...capability.permissions].sort(), wakePermissions);
});

test('the inlined device-state manifest declares exactly the listener pair', () => {
  const source = readFileSync(join(root, 'src-tauri/build.rs'), 'utf8');
  const declared = /InlinedPlugin::new\(\)\s*\.commands\(&\[([^\]]*)\]\)/u.exec(source);
  assert.ok(declared, 'device-state must be declared as an inlined plugin');
  assert.deepEqual([...declared[1].matchAll(/"([a-z_]+)"/gu)].map((match) => match[1]), ['register_listener', 'remove_listener']);
  assert.match(source, /\.plugin\("device-state", device_state\)/u);
});

test('no capability grants a plugin permission beyond the request wake', () => {
  const directory = join(root, 'src-tauri/capabilities');
  const files = readdirSync(directory).filter((name) => name.endsWith('.json')).sort();
  assert.deepEqual(files, ['android-request-wake.json', 'main.json']);
  for (const name of files) {
    const capability = JSON.parse(readFileSync(join(directory, name), 'utf8'));
    for (const permission of capability.permissions) {
      if (typeof permission !== 'string' || permission.includes(':')) {
        assert.ok(name === 'android-request-wake.json' && wakePermissions.includes(permission), `${name}: ${JSON.stringify(permission)} is not the request wake`);
      }
    }
  }
});
